"""initial schema

Revision ID: abe9b8f84be7
Revises: 
Create Date: 2026-07-13 10:31:20.583527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe9b8f84be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('severity_hint', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_incidents_fingerprint'), 'parsed_incidents', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_parsed_incidents_id'), 'parsed_incidents', ['id'], unique=False)
    op.create_table('raw_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_incidents_id'), 'raw_incidents', ['id'], unique=False)
    op.create_table('agent_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_incident_id'], ['raw_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_findings_agent_name'), 'agent_findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_findings_id'), 'agent_findings', ['id'], unique=False)
    op.create_table('github_action_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('issue_url', sa.String(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_incident_id'], ['raw_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_action_findings_id'), 'github_action_findings', ['id'], unique=False)
    op.create_table('remediation_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_incident_id'], ['raw_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_findings_id'), 'remediation_findings', ['id'], unique=False)
    op.create_table('root_cause_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_incident_id'], ['raw_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_cause_findings_id'), 'root_cause_findings', ['id'], unique=False)
    op.create_table('severity_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_incident_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_incident_id'], ['raw_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_severity_findings_id'), 'severity_findings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_severity_findings_id'), table_name='severity_findings')
    op.drop_table('severity_findings')
    op.drop_index(op.f('ix_root_cause_findings_id'), table_name='root_cause_findings')
    op.drop_table('root_cause_findings')
    op.drop_index(op.f('ix_remediation_findings_id'), table_name='remediation_findings')
    op.drop_table('remediation_findings')
    op.drop_index(op.f('ix_github_action_findings_id'), table_name='github_action_findings')
    op.drop_table('github_action_findings')
    op.drop_index(op.f('ix_agent_findings_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_agent_name'), table_name='agent_findings')
    op.drop_table('agent_findings')
    op.drop_index(op.f('ix_raw_incidents_id'), table_name='raw_incidents')
    op.drop_table('raw_incidents')
    op.drop_index(op.f('ix_parsed_incidents_id'), table_name='parsed_incidents')
    op.drop_index(op.f('ix_parsed_incidents_fingerprint'), table_name='parsed_incidents')
    op.drop_table('parsed_incidents')
    # ### end Alembic commands ###
