from app.agentic_workflow.state.incident_state import IncidentState
from app.mcp_client.github_mcp_client import GitHubMCPClient
from typing import Dict,Any
from app.core.logger import logger

async def github_action_node(state: IncidentState) -> Dict[str,Any]:
    title = (
        f"[{state.get('severity_level', 'P?')}] "
        f"{state.get('service_name', 'unknown-service')} — "
        f"{state.get('error_type', 'unknown error')}"
    )
    body = state.get("github_issue_body") or "No issue body generated by remediation agent."
    severity = state.get("severity_level") or "unknown"

    try:
        result = await GitHubMCPClient().create_github_issue(
            title=title,
            body=body,
            severity=severity,
        )
        logger.info(f"GitHub issue created: {result.get('issue_url')}")
        return {
            "github_issue_url": result.get("issue_url"),
            "github_issue_number": result.get("issue_number"),
        }
    except Exception as e:
        logger.error(f"GitHub MCP tool call failed: {e}", exc_info=True)
        return {"github_issue_url": None, "github_issue_number": None}